name: pipeline.yml CI/CD

on:
  push:
    branches:
      - lab9


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: '.'
          
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-
          
      - name: setup pnpm environment
        uses: pnpm/action-setup@v2
        with:
          version: 7.1.7
            
      - name: build
        run: |
          pnpm install
          pnpm build
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: vue2048
          path: dist/
